services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://root:${POSTGRES_PASSWORD:-mysecretpassword}@db:5432/local
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-dummy_client_id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-dummy_client_secret}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:3000/login/google/callback}
      - ORIGIN=http://localhost:3000
    depends_on:
      - db
volumes:
  pgdata:
